// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LoginByEmail(arg1:string,arg2:string):Promise<void>;

export function RegisterByEmail(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
