// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function LoginByEmail(arg1, arg2) {
  return window['go']['app']['App']['LoginByEmail'](arg1, arg2);
}

export function RegisterByEmail(arg1, arg2) {
  return window['go']['app']['App']['RegisterByEmail'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
